### ISSUE TITLE
Skip markers

### ISSUE THREAD

**Issue by hackebrot** [hackebrot/qutebrowser#10]
I spotted several places where `unittest.skip` is being used. We should replace them with according `py.test` markers.

**Comment by The-Compiler** [comment]
There are basically two kinds of skipped tests:
- Tests which are here, but which are currently broken but shouldn't generate a failure (because it's not so important to fix the underlying issues right now). Those are the ones in `test/utils/test_debug.py`. Maybe those should be marked as "expected failure" instead?
- Tests which only run on Linux/Windows/POSIX - those are the ones in `utils/test_standarddir.py` and `browser/http/test_content_disposition.py`.

**Comment by nicoddemus** [comment]
In my opinion, if a test is still in `xUnit` style, it is fine to leave the `unittest.skipUnless` decorators. But once we convert a `xUnit` style to `pytest`, we should definitely use `pytest.mark.skipif`.

That being said, because we are now using `pytest`'s runner, converting all to `pytest.mark.skipif` will work even for `xUnit` tests, so I don't mind it. :smile:

**Comment by hackebrot** [comment]
I'll be happy to change `test_debug.py` to use `xfail` instead. Additionally I will have a look into the modules @The-Compiler mentioned! :relaxed:

**Comment by nicoddemus** [comment]
I got a few minutes on my hands and converted `test_standardir` to pytest style instead, using `monkeypatch` and `tmpdir`. :smile:

@hackebrot and @The-Compiler, please take a look at the [commit](https://github.com/hackebrot/qutebrowser/commit/298892a4a8a254280c97417b63cb44c654d2788e).

**Comment by hackebrot** [comment]
Fair enough :stuck_out_tongue_winking_eye: 

I'll have a look at your changes tomorrow hopefully. Need to get some sleep and catch my train in the morning :train:

**Comment by The-Compiler** [comment]
I think we can close this, right?

**Comment by nicoddemus** [comment]
I guess so... @hackebrot?

**Comment by hackebrot** [comment]
Sure :triumph:
